### ISSUE TITLE
TX_Curr and Tx New issues/suggested changes 

### ISSUE THREAD

**Issue by PCOZim** [pepfar-datim/Beta-Pack-Feedback#20]
•	FY19 TX_CURR Target is being used as the FY20 starting point. In the event that we have already surpassed the FY19 target in FY18 (and this is not uncommon), we will have an under-estimate. It would help to add the current FY18 results so that we take whatever is the MAX between the current FY18 result and the FY19 Target as our starting point
•	This current datapack introduces the TX_CURR growth factor as an input in calculating FY20 target. This TX_CURR growth is set only for Age/Sex groups for the ScaleUp Saturation and ScaleUp Aggressive PSNUs. We need flexibility to set this growth rate based on District gap to saturation, on top of the already provided growth by Age/Sex. 
•	FY20 TX_NEW target for <1 age group should equal the number of HIV+ infants identified linked to ART (PMTCT_EID tab). However in the TX tab the same total number of infants linked to ART is repeated for <1 Female and <1 male, which doubles the total number of <1 on ART. The calculation need to split the number from PMTCT_EID between the <1 Females and Males in the TX_NEW target
•	FY19 TX CURR targets age/sex distribution has been used to distribute TX_NEW and subsequent targets to their age/sex groups. This will apportion more targets to age bands based on the TX_CURR case load and not based on gap or need. FY19 TX_CURR Target distribution of age/sex bands might not be appropriate for TX_NEW, we need to be informed by the need or gap existing within the different age bands, 
•	The new datapack assumes we will get our PLHIV estimates split by the finer age/sex bands, which was not the case for the 0-14 age group during COP18 planning. I hope we will be able to get the fine age/sex bands this year, and if not there will be a need to have course disaggregate for this 0-14 age group.

**Comment by jacksonsj** [comment]
Hi @PCOZim. See some comments/answers below.

•	FY19 TX_CURR Target is being used as the FY20 starting point. In the event that we have already surpassed the FY19 target in FY18 (and this is not uncommon), we will have an under-estimate. It would help to add the current FY18 results so that we take whatever is the MAX between the current FY18 result and the FY19 Target as our starting point
`The FY19 Expected Results column initially includes your FY19 target, but you should update this to reflect what you believe your actual end point at end of FY19 will be. This should then resolve issues where FY19 targets either over- or underestimate expected results.`

•	This current datapack introduces the TX_CURR growth factor as an input in calculating FY20 target. This TX_CURR growth is set only for Age/Sex groups for the ScaleUp Saturation and ScaleUp Aggressive PSNUs. We need flexibility to set this growth rate based on District gap to saturation, on top of the already provided growth by Age/Sex.
```
You're right that the current Data Pack does not automatically set TX_CURR based on gaps to coverage/saturation. More detail will need to be included in OGAC guidance, but you can still get to this through iteration/simulation as follows:

1. Set Prioritizations
2. Set TX_CURR growth rates in Summary tab
3. Adjust TX_CURR growth rates more specifically in TX tab.
4. Compare TX_CURR targets against _Targeted National ART Coverage (FY20)_ column to see impact of TX_CURR growth rate on expected coverage.
5. Adjust TX_CURR growth rate up or down to move targeted coverage closer to goal.
```

•	FY20 TX_NEW target for <1 age group should equal the number of HIV+ infants identified linked to ART (PMTCT_EID tab). However in the TX tab the same total number of infants linked to ART is repeated for <1 Female and <1 male, which doubles the total number of <1 on ART. The calculation need to split the number from PMTCT_EID between the <1 Females and Males in the TX_NEW target
`This is a bug. Thank you for catching this. I've made this change and it will be reflected in the next release of the Data Pack.`

•	FY19 TX CURR targets age/sex distribution has been used to distribute TX_NEW and subsequent targets to their age/sex groups. This will apportion more targets to age bands based on the TX_CURR case load and not based on gap or need. FY19 TX_CURR Target distribution of age/sex bands might not be appropriate for TX_NEW, we need to be informed by the need or gap existing within the different age bands
`The primary driver of TX_NEW is TX_NET_NEW. This is not specifically called out as a separate column right now (Would this be helpful @PCOZim?), but is incorporated in the formula for TX_NEW. You're right that TX_NET_NEW is not automatically determined by gap to coverage levels by each age/sex group, as it was last year, but you can adjust this by changing TX_CURR growth rates specific to each age/sex group and then compare against the **Targeted National ART coverage (FY20)** column to determine gap to coverage. Does this answer the issue? If not, could you describe an additional feature that may help?`

•	The new datapack assumes we will get our PLHIV estimates split by the finer age/sex bands, which was not the case for the 0-14 age group during COP18 planning. I hope we will be able to get the fine age/sex bands this year, and if not there will be a need to have course disaggregate for this 0-14 age group.
`More detail coming directly from UNAIDS/Avenir during January trainings from them, but Spectrum will now output estimates by 5 yr age bands (and <1) and down to SNU 1, 2, or 3 depending on your prioritization level. This data can be exported from Spectrum in a CSV file structured as you saw it in the Spectrum tab of the Beta Pack, so that you can copy/paste or directly import this data there.`


@PCOZim - If I haven't answered any questions completely, could you add more? I'll track down additional answers for you.

**Comment by PCOZim** [comment]
Thank you. I will share the answers with the SI team and see if they have any follow-up questions. Many people are now out for the Christmas holiday but we will follow-up.

**Comment by WilliamShiflett** [comment]
Issue moved to [pepfar-datim/COP-19-Target-Setting #236](https://github.com/pepfar-datim/COP-19-Target-Setting/issues/236) via [**ZenHub**](https://www.zenhub.com/)
